pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch: 'dev', credentialsId: 'edututorc', url: 'https://github.com/TLS-The-Last-Stop/edututor'
            }
        }
        stage('Build') {
            steps {
                script {
                    def jenkinsfilePath = 'Backend/edututor/Jenkinsfile'
                    load jenkinsfilePath
                }
            }
        }
    }
}
